### ISSUE TITLE
Stuck at step 10 and 11

### ISSUE THREAD

**Issue by WingsOfCoronia** [dmarov/chamd#12]
Hello! I'm stuck at these step:
Step 10 with "npm run all", here's the logs:
C:\Users\ADMIN\Desktop\chamd>npm run all

> @ all C:\Users\ADMIN\Desktop\chamd
> node --unhandled-rejections=strict ./scripts/builder.js all

Generating  driver ...
C:\Users\ADMIN\Desktop\chamd\scripts\context.js:63
        fs.rmSync(this.cmakeConfigPath);
           ^

TypeError: fs.rmSync is not a function
    at Context.purge (C:\Users\ADMIN\Desktop\chamd\scripts\context.js:63:12)
    at async Context.all (C:\Users\ADMIN\Desktop\chamd\scripts\context.js:43:9)
    at async C:\Users\ADMIN\Desktop\chamd\scripts\builder.js:20:13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ all: `node --unhandled-rejections=strict ./scripts/builder.js all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Roaming\npm-cache\_logs\2022-11-23T15_50_47_268Z-debug.log

Step 11: I don't seem to see any of "dist" file in your repositories

Many regards

**Comment by dmarov** [comment]
It has to be something wrong with nodejs version.
Check
```
node --version
```
Version 14.x.x is required

**Comment by WingsOfCoronia** [comment]
Yes i do install the correct version of Nodejs (14.4.0.0), reinstalled and still failed many times...

Thanks

**Comment by dmarov** [comment]
try version '14.14.0' or greater - this is the version when `fs.rmSync` was added
if no avail, then also try '19.1.0' - I've just checked it worked

**Comment by WingsOfCoronia** [comment]
Now it appears to have more problems the more i fix them, if you have time for a bit can you team-view me? I'm completely blind as a bat, that will help me a lot!

**Comment by dmarov** [comment]
If you have other issue then you are welcome to open another issue here
I close this one
