### ISSUE TITLE
Bypass EAC for Chivalry2

### ISSUE THREAD

**Issue by tsvetkovsecurity** [dmarov/chamd#14]
Hey my bro. Can you please help me to bypass EAC for Game (Chivalry2) and run the CheatEngine (speedhack) ?

I am able to pay you ! Discord:  ivanyNano#5967

**Comment by dmarov** [comment]
Usage of Cheat Engine's speedhack on anti-cheat protected games is not straightforward, and you won't be able to use it on EAC protected game easily.

There's article about how speedhack works:
https://stackoverflow.com/questions/17512906/how-does-cheatengines-speed-hack-work

And this is what you're dealing with:
https://guidedhacking.com/threads/how-to-bypass-anticheat-start-here-beginners-guide.9882/
