### ISSUE TITLE
Outdated???

### ISSUE THREAD

**Issue by WeLoveGaming** [dmarov/chamd#2]
Hey!
I noticed this project hasn't been updated in awhile, is this bypass outdated/ detected?
Also, would this work for a Dead By Daylight cheat?

**Comment by ElectroGamesYT** [comment]
Would this work for a Dead By Daylight cheat?

**Comment by dmarov** [comment]
>  is this bypass outdated/ detected?

No I just lost interest in online games hacking. I don't think it is outdated (you'll be able to use it to mess with memory), and it might be detected (you can get banned for using it).

> Also, would this work for a Dead By Daylight cheat?

Yes, because DBD uses EAC, and this is exact anti-cheat which I used to test this bypass.
