### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by micpitbull** [dmarov/chamd#3]
It is still working for me on Win11 

and as you showed in your Video Blue Screens comes after a while but until then it is possible to use CE

any chance you can get the debugger running?

**Comment by dmarov** [comment]
> Blue Screens comes after

**Comment by dmarov** [comment]
> Blue Screens comes after a while
I recommend to use [EFIGuard](https://github.com/Mattiwatti/EfiGuard) because DSEFix is outdated
Successful debugger attach can be achieved by using Cheat Engine 7.3, I explained how to do it on my YT channel.
