### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by OldJewish** [dmarov/chamd#5]
After I Run "yarn all"
i get "Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT" and i tried to research but nothing worked
![Screenshot_1](https://user-images.githubusercontent.com/99241652/152935185-7b72ef05-eef5-4bed-a993-19f8e2579e22.png)

**Comment by dmarov** [comment]
It doesn't look like `cmd.exe` is detected as it should which doesn't make sense.
Try to run it in terminal other than Cmder. Regular command prompt is a good option.

**Comment by OldJewish** [comment]
> It doesn't look like `cmd.exe` is detected as it should which doesn't make sense. Try to run it in terminal other than Cmder. Regular command prompt is a good option.

idk I tried cmder, command prompt, and powershell. Cmd exist in that dir and I got it in my PATH in system vars but thx for the reply tho.

**Comment by LnYo-Cly** [comment]
> > It doesn't look like `cmd.exe` is detected as it should which doesn't make sense. Try to run it in terminal other than Cmder. Regular command prompt is a good option.
> 
> idk I tried cmder, command prompt, and powershell. Cmd exist in that dir and I got it in my PATH in system vars but thx for the reply tho.

I also encountered such a problem, how did you solve it?thanks

**Comment by OldJewish** [comment]
> > > It doesn't look like `cmd.exe` is detected as it should which doesn't make sense. Try to run it in terminal other than Cmder. Regular command prompt is a good option.
> > 
> > 
> > idk I tried cmder, command prompt, and powershell. Cmd exist in that dir and I got it in my PATH in system vars but thx for the reply tho.
> 
> I also encountered such a problem, how did you solve it?thanks

I haven't found a solution yet. I got tired of looking though but I'm sure there's a fix somewhere.

**Comment by dmarov** [comment]
There is very similar issue https://stackoverflow.com/a/55074891
It looks like `cwd` path is ok. Maybe nodejs doesn't have permission to run `cmd.exe` for some reason or ComSpec variable is messed up.

**Comment by SnowQT** [comment]
hey , did someone figured the issue  ?

![image](https://user-images.githubusercontent.com/10016273/157914978-4e5019e4-d0a6-450e-a7b1-9ddc4222b0b9.png)
