### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by LnYo-Cly** [dmarov/chamd#7]
![image](https://user-images.githubusercontent.com/47201396/154297722-dc53b1b6-f62b-4c5f-bf68-07b2d722c408.png)

i can't solve it

**Comment by dmarov** [comment]
Take a look at this issue https://stackoverflow.com/questions/35603506/unable-to-build-wdk-10-samples-with-vc2015-without-modifying-windows-headers
It's probably because of **different versions of Win SDK and WDK**

**Comment by LnYo-Cly** [comment]
> Take a look at this issue https://stackoverflow.com/questions/35603506/unable-to-build-wdk-10-samples-with-vc2015-without-modifying-windows-headers It's probably because of **different versions of Win SDK and WDK**

thanks，I solved it. But I met a new mistake
![image](https://user-images.githubusercontent.com/47201396/154652170-bf308b10-5248-4cb3-8096-0a010d6bb1e2.png)

**Comment by dmarov** [comment]
Well, I don't know why `signtool` requires algorithm all of a sudden, but you could try to remove signing from build sequence.
For that you need to comment out this line https://github.com/dmarov/chamd/blob/e4c42845a3cd948f1a88313799a43e6c51f4bdb7/scripts/cmd.js#L35
