### ISSUE TITLE
Thanks for your services but i am facing a problem with "UnhandledPromiseRejection"

### ISSUE THREAD

**Issue by GDRMgh** [dmarov/chamd#9]
![Error](https://user-images.githubusercontent.com/107893017/174708812-272d8604-755c-4cb1-916e-4f0c1a47b272.jpg)
I did every step as instructed but i am hitting a wall, i install different versions of node js change npm, npm.cmd, npx, npx.cmd and replace prefix -g with prefix --location=global. I tried downgraded with  npm install -g npm@"V" and reinstall and dis from scrap more times than i can count and still no luck. someone can help me please!

**Comment by dmarov** [comment]
Error tells me that there's some promise failed and was not handled.
1. pull latest changes from `master`
2. try nodejs 14.16.1, which is what I use
If no success, then I'll need more info about this error.
